---
title: "Urban Growth Modeling"
author: "Javier Fernandez, Lu Yii Wong"
date: "2024-04-30"
output: html_document
---

# 1: Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r load_packages, message=FALSE, warning=FALSE, results = "hide"}
library(tidyverse)
library(sf)
library(raster)
library(knitr)
library(kableExtra)
library(tidycensus)
library(tigris)
library(FNN)
library(tiff)
#library(QuantPsyc) # JE Note: in R 4.1, QuantPsyc package not available.
library(caret)
library(yardstick)
library(pscl)
library(plotROC) 
library(ggrepel)
library(pROC)
library(grid)
library(gridExtra)
library(viridis)
library(igraph)

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

palette2 <- c("#41b6c4","#253494")
palette4 <- c("#a1dab4","#41b6c4","#2c7fb8","#253494")
palette5 <- c("#ffffcc","#a1dab4","#41b6c4","#2c7fb8","#253494")
palette10 <- c("#f7fcf0","#e0f3db","#ccebc5","#a8ddb5","#7bccc4",
               "#4eb3d3","#2b8cbe","#0868ac","#084081","#f7fcf0")
```

```{r, warning = FALSE, message = FALSE}
#this function converts a column in to quintiles. It is used for mapping.
quintileBreaks <- function(df,variable) {
    as.character(quantile(df[[variable]],
                          c(.01,.2,.4,.6,.8),na.rm=T))
}

#This function can be used to convert a polygon sf to centroids xy coords.
xyC <- function(aPolygonSF) {
  as.data.frame(
    cbind(x=st_coordinates(st_centroid(aPolygonSF))[,1],
          y=st_coordinates(st_centroid(aPolygonSF))[,2]))
} 

#this function convert a raster to a data frame so it can be plotted in ggplot
rast <- function(inRaster) {
  data.frame(
    xyFromCell(inRaster, 1:ncell(inRaster)), 
    value = getValues(inRaster)) }
```

# 2: Data Wrangling

## 2.1: Land Cover

```{r load_data, warning = FALSE, message = FALSE, results = "hide"}

njMSA <- st_read("/Users/luyiiwong/Documents/GitHub/LandUseModeling_HW5/Data/nj_counties_msa.geojson")

lc_2011 <- raster("/Users/luyiiwong/Documents/GitHub/LandUseModeling_HW5/Data/lc_nj_msa_2011.tif.aux/lc_nj_msa_2011.tif")

#resampled version
lc_2021 <- raster("/Users/luyiiwong/Documents/GitHub/LandUseModeling_HW5/Data/lc_2021_resampled/lc_2021_resampled.tif")

# lc_2021 = raster("/Users/luyiiwong/Documents/GitHub/LandUseModeling_HW5/Data/nlcd_2021_landcover.tif.aux/nlcd_2021_landcover.tif")

#lc_change = raster("/Users/luyiiwong/Documents/GitHub/LandUseModeling_HW5/Data/nlcd_nj_msa/nlcd_nj_msa.tif")
```

```{r}
### ATTEMPT TO MAKE THE RESOLUTION 4000 TO FIT THE FISHNET

# resampling to make sure the resolutions are the same
lc_2021_resampled <- resample(lc_2021, lc_2011, method = "bilinear")
res(lc_2011)
res(lc_2021_resampled)

#defining raster resolution
new_res <- c(197.9719, 154.8713) * 197.9719 / 4000

lc_2011_resampled <- aggregate(lc_2011, fact = 4000/res(lc_2011))
res(lc_2011_resampled)
lc_2021_resampled <- aggregate(lc_2021_resampled, fact = 4000/res(lc_2021_resampled))
res(lc_2021_resampled)


#lc_2011_resampled <- resample(lc_2011, res = new_res, method = "bilinear")
#lc_2021_resampled <- resample(lc_2021_resampled, res = new_res, method = "bilinear")

#reclassification matrix
reclassMatrix <- 
  matrix(c(
    0,12,0,
    12,24,1,
    24,Inf,0),
  ncol=3, byrow=T)

# reclassifying lc to developed and not developed
developed_2011 <- reclassify(lc_2011_resampled,reclassMatrix)
developed_2021 <- reclassify(lc_2021_resampled,reclassMatrix)

res(developed_2011)
res(developed_2021)

# creating a land cover change dataframe
development_change <- developed_2011 + developed_2021

hist(development_change)


development_change[development_change != 1] <- NA

ggplot() +
  geom_sf(data=njMSA) +
  geom_raster(data=rast(development_change) %>% na.omit, 
              aes(x,y,fill=as.factor(value))) +
  scale_fill_viridis(discrete=TRUE, name ="Land Cover\nChange") + 
  labs(title="Development land use change") +
  mapTheme
```

```{r}
### ATTEMPT TO CREATE A TEMPLATE RASTER

template_raster <- raster(extent(lc_2011), resolution = 4000, 
                          crs = st_crs(lc_2011)$proj4string)

res(lc_2011)
projected_raster <= projectRaster(from = lc_2011, to = template_raster)
```


```{r}

lc_change <- lc_2011 + lc_2021_resampled
lc_change_filtered <- mask(lc_change, lc_change >0)

# WHY DOES THIS PART TAKE SO LONG TO RUN?
# Land Cover Change, 2011-2021
ggplot() +
  geom_sf(data=njMSA) +
  geom_raster(data=rast(lc_change_filtered) %>% na.omit, 
              aes(x,y,fill=as.factor(value))) +
  scale_fill_viridis(direction = -1, discrete=TRUE, name ="Land Cover\nChange") +
  labs(title = "Land Cover Change, 2011-2021") +
  mapTheme +
  theme(legend.direction="horizontal")

```

## creating fishnet

```{r}
njMSA_fishnet <- 
  st_make_grid(njMSA, 4000) %>%
  st_sf()

njMSA_fishnet <-
  njMSA_fishnet[njMSA,]

ggplot() +
  geom_sf(data=njMSA_fishnet) +
  labs(title="Fishnet, 4000 Foot Resolution") +
  mapTheme
```

```{r}
changePoints <-
  rasterToPoints(development_change) %>%
  as.data.frame() %>%
  st_as_sf(coords = c("x", "y"), crs = st_crs(njMSA_fishnet))

fishnet <- 
  aggregate(changePoints, njMSA_fishnet, sum) %>%
  mutate(development_change = ifelse(is.na(development_change),0,1),
         development_change = as.factor(development_change))

ggplot() +
  geom_sf(data=njMSA) +
  geom_point(data=fishnet, 
             aes(x=xyC(fishnet)$x, y=xyC(fishnet)$y, colour=development_change)) +
  scale_colour_manual(values = palette2,
                      labels=c("No Change","New Development"),
                      name = "") +
  labs(title = "Land Cover Development Change", subtitle = "As fishnet centroids") +
  mapTheme
```

```{r, warning = FALSE, message = FALSE}
development_change[development_change != 1] <- NA

ggplot() +
  geom_sf(data=njMSA) +
  geom_raster(data=rast(development_change) %>% na.omit, 
              aes(x,y,fill=as.factor(value))) +
  scale_fill_viridis(discrete=TRUE, name ="Land Cover/nChange") + 
  labs(title="Development land use change") +
  mapTheme

aggregate(development_change, fact = 20)
```

## plot MSA

```{r plot_msa, warning= FALSE, message= FALSE}
ggplot() +
  geom_sf(data=njMSA) +
  geom_raster(data=rast(lc_change) %>% na.omit %>% filter(value > 0), 
              aes(x,y,fill=as.factor(value))) +
  scale_fill_viridis(direction = -1, discrete=TRUE, name ="Land Cover\nChange") +
  labs(title = "Land Cover Change, 2011-2021") +
  mapTheme +
  theme(legend.direction="horizontal")
```

## reclassify land cover change

```{r, warning = FALSE, message = FALSE}
reclassMatrix <- matrix(c(
  0, 2, 0,
  3, 3, 1,
  3, Inf, 0),
  ncol = 3, byrow = TRUE)

reclassMatrix
```

```{r, warning = FALSE, message = FALSE}
lc_change2 <- 
  reclassify(lc_change,reclassMatrix)

lc_change2[lc_change2 < 1] <- NA

names(lc_change2) <- "lc_change"

ggplot() +
  geom_sf(data=njMSA) +
  geom_raster(data=rast(lc_change2) %>% na.omit, 
              aes(x,y,fill=as.factor(value))) +
  scale_fill_viridis(discrete=TRUE, name ="Land Cover\nChange") + 
  labs(title="Development Land Use Change") +
  mapTheme
```

## fishnet

```{r, warning = FALSE, message = FALSE}
njMSA_fishnet <- 
  st_make_grid(njMSA, 2000) %>%
  st_sf()

njMSA_fishnet <-
  njMSA_fishnet[njMSA,]

ggplot() +
  geom_sf(data=njMSA_fishnet) +
  labs(title="Fishnet, 2000 Foot Resolution") +
  mapTheme
```

```{r, warning = FALSE, message = FALSE}
changePoints <-
  rasterToPoints(lc_change2) %>%
  as.data.frame() %>%
  st_as_sf(coords = c("x", "y"), crs = st_crs(njMSA_fishnet))

fishnet <- 
  aggregate(changePoints, njMSA_fishnet, sum) %>%
  mutate(lc_change = ifelse(is.na(lc_change),0,1),
         lc_change = as.factor(lc_change))

ggplot() +
  geom_sf(data=njMSA) +
  geom_point(data=fishnet, 
             aes(x=xyC(fishnet)$x, y=xyC(fishnet)$y, colour=lc_change)) +
  scale_colour_manual(values = palette2,
                      labels=c("No Change","New Development"),
                      name = "") +
  labs(title = "Land Cover Development Change", subtitle = "As fishnet centroids") +
  mapTheme
```

# 2.2 land cover change 2011

```{r, warning = FALSE, message = FALSE}
lc_2011 <- raster("/Users/luyiiwong/Documents/GitHub/LandUseModeling_HW5/Data/lc_nj_msa_2011.tif.aux/lc_nj_msa_2011.tif")

ggplot() +
  geom_sf(data=njMSA) +
  geom_raster(data=rast(lc_2011) %>% na.omit %>% filter(value > 0), 
              aes(x,y,fill=as.factor(value))) +
  scale_fill_viridis(discrete=TRUE, name ="") +
  labs(title = "Land Cover, 2011") +
  mapTheme +
  theme(legend.direction="horizontal")

#### trying to recolor based on MRLC categorization
## FIGURE THIS OUT
#LCcodes <- unique(lc_2011)

LCnames <-c(
  "Water",
  "DevelopedOpen",
  "DevelopedLow",
  "DevelopedMed",
  "DevelopedHigh",
  "Barren",
  "DeciduousForest",
  "EvergreenForest",
  "MixedForest",
  "ShrubScrub",
  "GrassHerbaceous",
  "PastureHay",
  "CultCrops",
  "WoodyWetlands",
  "EmergentHerbWet")

ggplot
```

## 2.2.1: Reclassifying land use type

```{r, warning = FALSE, message = FALSE}
developed <- lc_2011 == 21 | lc_2011 == 22 | lc_2011 == 23 | lc_2011 == 24
forest <- lc_2011 == 41 | lc_2011 == 42 | lc_2011 == 43 
farm <- lc_2011 == 81 | lc_2011 == 82 
wetlands <- lc_2011 == 90 | lc_2011 == 95 
otherUndeveloped <- lc_2011 == 52 | lc_2011 == 71 | lc_2011 == 31 
water <- lc_2011 == 11

names(developed) <- "developed"
names(forest) <- "forest"
names(farm) <- "farm"
names(wetlands) <- "wetlands"
names(otherUndeveloped) <- "otherUndeveloped"
names(water) <- "water"
```

```{r, warning = FALSE, message = FALSE}
aggregateRaster <- function(inputRasterList, theFishnet) {
  #create an empty fishnet with the same dimensions as the input fishnet
  theseFishnets <- theFishnet %>% dplyr::select()
  #for each raster in the raster list
  for (i in inputRasterList) {
  #create a variable name corresponding to the ith raster
  varName <- names(i)
  #convert raster to points as an sf
    thesePoints <-
      rasterToPoints(i) %>%
      as.data.frame() %>%
      st_as_sf(coords = c("x", "y"), crs = st_crs(theFishnet)) %>%
      filter(.[[1]] == 1)
  #aggregate to the fishnet
    thisFishnet <-
      aggregate(thesePoints, theFishnet, length) %>%
      mutate(!!varName := ifelse(is.na(.[[1]]),0,1))
  #add to the larger fishnet
    theseFishnets <- cbind(theseFishnets,thisFishnet)
  }
  #output all aggregates as one large fishnet
   return(theseFishnets)
  }
```

```{r, warning = FALSE, message = FALSE}
theRasterList <- c(developed,forest,farm,wetlands,otherUndeveloped,water)


## DID NOT RUN THIS SECTION ##
aggregatedRasters <-
  aggregateRaster(theRasterList, njMSA_fishnet) %>%
  dplyr::select(developed,forest,farm,wetlands,otherUndeveloped,water) %>%
  mutate_if(is.numeric,as.factor)

aggregatedRasters %>%
  gather(var,value,developed:water) %>%
  st_cast("POLYGON") %>%    #just to make sure no weird geometries slipped in
  mutate(X = xyC(.)$x,
         Y = xyC(.)$y) %>%
  ggplot() +
    geom_sf(data=njMSA) +
    geom_point(aes(X,Y, colour=as.factor(value))) +
    facet_wrap(~var) +
    scale_colour_manual(values = palette2,
                        labels=c("Other","Land Cover"),
                        name = "") +
    labs(title = "Land Cover Types, 2011",
         subtitle = "As fishnet centroids") +
   mapTheme
```

# 2.3: ACS Data

```{r}
# setting up api key 
census_api_key("b83a23afee4a8ed0fa131e449869e6577b87151e", overwrite = TRUE, install = TRUE)
```

```{r}
# creating list for selected counties
selected_counties <- c("Bergen County, New Jersey", "Hudson County, New Jersey", "Passaic County, New Jersey" , 
                       "Middlesex County, New Jersey", "Monmouth County, New Jersey", "Ocean County, New Jersey", 
                       "Somerset County, New Jersey", "Essex County, New Jersey", "Union County, New Jersey",
                       "Morris County, New Jersey", "Sussex County, New Jersey", "Hunterdon County, New Jersey",
                       "Mercer County, New Jersey", "Warren County, New Jersey")

# pulling data from census for 2011
dat_2011 <- get_acs(geography = "county", 
          variables = c("B01003_001E",
                        "B19013_001E"), 
          year = 2011, 
          state = "NJ", 
          geometry = TRUE, 
          output = "wide") %>%
  rename(total_pop = B01003_001E,
         median_hh_income = B19013_001E) %>%
  dplyr::select(GEOID, NAME, total_pop, median_hh_income, geometry) %>%
  filter(NAME %in% selected_counties)



# pulling data from census for 2021
dat_2021 <- get_acs(geography = "county", 
          variables = c("B01003_001E",
                        "B19013_001E"), 
          year = 2021, 
          state = "NJ", 
          geometry = TRUE, 
          output = "wide") %>%
  rename(total_pop = B01003_001E,
         median_hh_income = B19013_001E) %>%
  dplyr::select(GEOID, NAME, total_pop, median_hh_income, geometry) %>%
  filter(NAME %in% selected_counties)

```

## plotting population

```{r, warning = FALSE, message = FALSE, fig.height= 8, fig.width= 11}
## BY COUNTY, NO NEED ##
grid.arrange(
ggplot() +
  geom_sf(data = dat_2011, aes(fill=factor(ntile(total_pop,5))), colour=NA) +
  scale_fill_manual(values = palette5,
                    labels=quintileBreaks(dat_2011,"total_pop"),
                   name="Quintile\nBreaks") +
  labs(title="Population, New Jersey (select counties): 2011") +
  mapTheme,

ggplot() +
  geom_sf(data = dat_2021, aes(fill=factor(ntile(total_pop,5))), colour=NA) +
  scale_fill_manual(values = palette5,
                    labels=quintileBreaks(dat_2021,"total_pop"),
                   name="Quintile\nBreaks") +
  labs(title="Population, New Jersey (select counties): 2021") +
  mapTheme, ncol=2)
```

# plotting by census tract

```{r}
# creating list for selected counties
selected_counties <- c("Bergen County, New Jersey", "Hudson County, New Jersey", "Passaic County, New Jersey" , 
                       "Middlesex County, New Jersey", "Monmouth County, New Jersey", "Ocean County, New Jersey", 
                       "Somerset County, New Jersey", "Essex County, New Jersey", "Union County, New Jersey",
                       "Morris County, New Jersey", "Sussex County, New Jersey", "Hunterdon County, New Jersey",
                       "Mercer County, New Jersey", "Warren County, New Jersey")

# pulling data from census for 2011
dat_2011_tract <- get_acs(geography = "tract", 
          variables = c("B01003_001E"), 
          year = 2011, 
          state = "NJ", 
          county = c("Bergen", "Hudson", "Passaic", "Middlesex", "Monmouth", "Ocean", "Somerset",
                     "Essex", "Union", "Morris", "Sussex", "Hunterdon", "Mercer", "Warren"),
          geometry = TRUE, 
          output = "wide") 

dat_2011_tract <- dat_2011_tract %>%
  rename(total_pop = B01003_001E) %>%
  dplyr::select(GEOID, NAME, total_pop, geometry)


ggplot() +
  geom_sf(data = dat_2011_tract, aes(fill=factor(ntile(total_pop,5))), colour=NA) +
  scale_fill_manual(values = palette5,
                    labels=quintileBreaks(dat_2011_tract,"total_pop"),
                   name="Quintile\nBreaks") +
  labs(title="Population, New Jersey by census tract: 2011") +
  mapTheme

# pulling data from census for 2021
dat_2021_tract <- get_acs(geography = "tract", 
          variables = c("B01003_001E"), 
          year = 2021, 
          state = "NJ", 
          county = c("Bergen", "Hudson", "Passaic", "Middlesex", "Monmouth", "Ocean", "Somerset",
                     "Essex", "Union", "Morris", "Sussex", "Hunterdon", "Mercer", "Warren"),
          geometry = TRUE, 
          output = "wide") 

dat_2021_tract <- dat_2021_tract %>%
  rename(total_pop = B01003_001E) %>%
  dplyr::select(GEOID, NAME, total_pop, geometry)


ggplot() +
  geom_sf(data = dat_2021_tract, aes(fill=factor(ntile(total_pop,5))), colour=NA) +
  scale_fill_manual(values = palette5,
                    labels=quintileBreaks(dat_2021_tract,"total_pop"),
                   name="Quintile\nBreaks") +
  labs(title="Population, New Jersey by census tract: 2021") +
  mapTheme

## grid arrange tract 2011 v 2021
grid.arrange(
ggplot() +
  geom_sf(data = dat_2011_tract, aes(fill=factor(ntile(total_pop,5))), colour=NA) +
  scale_fill_manual(values = palette5,
                    labels=quintileBreaks(dat_2011_tract,"total_pop"),
                   name="Quintile\nBreaks") +
  labs(title="Population, New Jersey (by tract): 2011") +
  mapTheme,

ggplot() +
  geom_sf(data = dat_2021_tract, aes(fill=factor(ntile(total_pop,5))), colour=NA) +
  scale_fill_manual(values = palette5,
                    labels=quintileBreaks(dat_2021_tract,"total_pop"),
                   name="Quintile\nBreaks") +
  labs(title="Population, New Jersey (by tract): 2021") +
  mapTheme, ncol=2)

## create a change in population map instead
# density/ prox to density

```

# 2.4 Highways

```{r, warning = FALSE, message = FALSE, results = "hide"}
njHighways <-
  st_read("/Users/luyiiwong/Documents/GitHub/LandUseModeling_HW5/Data/njroads_MSA.geojson") %>%
  st_zm() %>%
  st_transform(st_crs(njMSA)) %>%
  st_intersection(njMSA)
```

```{r plot_highway, warning = FALSE, message= FALSE}
ggplot() +
  geom_point(data=fishnet, 
             aes(x=xyC(fishnet)[,1], y=xyC(fishnet)[,2],colour=lc_change),size=1.5) +
  geom_sf(data= njHighways) +
  scale_colour_manual(values = palette2,
                      labels=c("No Change","New Development")) +
  labs(title = "New Development and Highways",
       subtitle = "As fishnet centroids") +
  mapTheme
```

```{r, warning = FALSE, message = FALSE}
emptyRaster <- lc_change
emptyRaster[] <- NA

highway_raster <- 
  as(njHighways,'Spatial') %>%
  rasterize(.,emptyRaster)

highway_raster_distance <- distance(highway_raster)
names(highway_raster_distance) <- "distance_highways"

highwayPoints <-
  rasterToPoints(highway_raster_distance) %>%
  as.data.frame() %>%
  st_as_sf(coords = c("x", "y"), crs = st_crs(njMSA_fishnet))

highwayPoints_fishnet <- 
  aggregate(highwayPoints, njMSA_fishnet, mean) %>%
  mutate(distance_highways = ifelse(is.na(distance_highways),0,distance_highways))

ggplot() +
  geom_sf(data=njMSA) +
  geom_point(data=highwayPoints_fishnet, aes(x=xyC(highwayPoints_fishnet)[,1], 
                                             y=xyC(highwayPoints_fishnet)[,2], 
                 colour=factor(ntile(distance_highways,5))),size=1.5) +
  scale_colour_manual(values = palette5,
                      labels=substr(quintileBreaks(highwayPoints_fishnet,"distance_highways"),1,8),
                      name="Quintile\nBreaks") +
  geom_sf(data= njHighways, colour = "red") +
  labs(title = "Distance to Highways",
       subtitle = "As fishnet centroids; Highways visualized in red") +
  mapTheme
```

# 2.5 Spatial Lag
